/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux gpcserver-VirtualBox 5.15.0-82-generic x86_64"
#define LGL_COMPILED "Fri Oct 27 12:35:59 CEST 2023"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
