/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux fmacpu 5.8.0-59-generic x86_64"
#define LGL_COMPILED "Wed Sep  8 09:57:54 EDT 2021"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
